version: "3.8"

services:
  ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./services/ui:/services/ui
    tty: true

dapp:
  build:
    context: ./services/dapp
    dockerfile: Dockerfile
  restart: always
  volumes:
    - ./services/dapp:/services/dapp/
  ports:
    - "8545:8545"
  tty: true
